#!/usr/bin/env bash
# Assemble the static publish root for the wasm edit-host — the runtime files any static
# host serves: web/ + dist/ as siblings, the cross-origin-isolation _headers at the root,
# plus the reference node server (web/serve.mjs) and a short README so the packaged
# tarball is turnkey ("extract and serve"). Run build.sh first — it produces
# dist/eh.{mjs,wasm} and the web/vendor/ highlighter + msgpack assets this copies.
#
# Single source of truth for the publish layout, shared by:
#   - netlify-build.sh / netlify-build-demo.sh (the Netlify deploys)
#   - build-demo.sh                            (the local python-demo site)
#   - .github/workflows/build.yml `edithost`   (the downloadable release tarball)
#
# Two flavors from one layout (the editor sources are identical; see build-config.js):
#   - standard editor (default): build-config.js stays `localHost: false`, no Pyodide.
#   - python demo (--demo):      build-config.js → `localHost: true`, plus the demo-only
#                                modules (local-host.mjs + pyodide-worker.mjs) and Pyodide
#                                vendored in, so a serverless `:terminal python …` works.
#
# Usage: package-site.sh [SITE_DIR] [--demo]   (SITE_DIR default ./_site, wiped each run)
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
site="$here/_site"
demo=0
for arg in "$@"; do
  case "$arg" in
    --demo) demo=1 ;;
    *) site="$arg" ;;
  esac
done

[ -f "$here/dist/eh.mjs" ] && [ -f "$here/dist/eh.wasm" ] || {
  echo "error: dist/eh.{mjs,wasm} missing — run build.sh before package-site.sh" >&2
  exit 1
}

# The page's relative imports require web/ and dist/ as siblings (index.html loads
# ./worker.mjs; worker.mjs loads ../dist/eh.mjs, statically imports ./rpc.mjs, and
# *dynamically* imports ./ts-indent.js — the optional tree-sitter indenter; highlight.js
# pulls in ./grammars.js + ./ts-sanitize.js). Copy every runtime file these reach — not
# the dev tooling, the Playwright verifiers, or package.json. serve.mjs *is* runtime here:
# it's the turnkey static server that sets the cross-origin-isolation headers (below).
rm -rf "$site"
mkdir -p "$site/web" "$site/dist"
cp "$here/dist/eh.mjs" "$here/dist/eh.wasm" "$site/dist/"
# build-config.js is required: worker.mjs statically imports it (the build-time feature
# flags). Without it the Worker fails to load.
cp "$here/web/index.html" "$here/web/worker.mjs" "$here/web/rpc.mjs" \
   "$here/web/build-config.js" "$here/web/highlight.js" "$here/web/grammars.js" \
   "$here/web/ts-sanitize.js" "$here/web/ts-indent.js" "$here/web/serve.mjs" "$site/web/"
[ -d "$here/web/vendor" ] && cp -r "$here/web/vendor" "$site/web/vendor"
# The first-party plugin bundle is demo-only; never ship it in the standard site (build.sh
# doesn't build it, but a local dev tree may have it vendored from a prior --demo run).
[ "$demo" = 1 ] || rm -rf "$site/web/vendor/plugins"

# Python-demo flavor: the local in-browser process host. Ship the demo-only modules, flip
# the build flag on, and vendor Pyodide (CPython → wasm) so `:terminal python …` runs. The
# standard flavor ships none of this and keeps the flag false.
if [ "$demo" = 1 ]; then
  cp "$here/web/local-host.mjs" "$here/web/pyodide-worker.mjs" "$site/web/"
  cat > "$site/web/build-config.js" <<'EOF'
// GENERATED by package-site.sh --demo — the python-demo site. See web/build-config.js.
export const BUILD = {
  localHost: true,
  plugins: true,
  demoSeed: true,
};
EOF
  # The recommended first-party plugin set + catppuccin, amalgamated into one preload bundle
  # (built from source — cloned at pinned commits; see build-plugins.sh). Idempotent: skipped
  # when already vendored. The blanket web/vendor copy above ships it.
  "$here/build-plugins.sh"
  mkdir -p "$site/web/vendor/plugins"
  cp "$here/web/vendor/plugins/plugins-bundle.lua" "$site/web/vendor/plugins/"
  # The first-boot OPFS seed: the demo project + guided tour + init.lua (worker.mjs fetches
  # these and writes them into OPFS once, gated by build-config demoSeed).
  cp -r "$here/web/demo-seed" "$site/web/demo-seed"
  PYODIDE_SRC="$here/web/node_modules/pyodide"
  [ -f "$PYODIDE_SRC/pyodide.mjs" ] || {
    echo "error: $PYODIDE_SRC missing — run build.sh (it npm-installs web deps) before --demo" >&2
    exit 1
  }
  mkdir -p "$site/web/vendor/pyodide"
  for f in pyodide.mjs pyodide.asm.mjs pyodide.asm.wasm python_stdlib.zip pyodide-lock.json; do
    cp "$PYODIDE_SRC/$f" "$site/web/vendor/pyodide/"
  done
  # The basedpyright LSP worker (built from source — there is no npm package; see
  # build-basedpyright.sh). Idempotent: the build is skipped when already vendored.
  "$here/build-basedpyright.sh"
  mkdir -p "$site/web/vendor/basedpyright"
  cp "$here/web/vendor/basedpyright/pyright.worker.js" "$site/web/vendor/basedpyright/"
fi

# Cross-origin-isolation headers for `_headers`-format hosts (Netlify / Cloudflare
# Pages): the Worker's run loop parks on a SharedArrayBuffer, granted only when the
# document is cross-origin isolated. Without these the page still runs but degrades to
# postMessage and timers never fire.
cp "$here/web/_headers" "$site/_headers"

# Send the bare root to /web/ (the app's imports resolve relative to that document URL).
# A `_redirects` file at the publish root so this holds on any `_headers`/`_redirects` host
# (Netlify / Cloudflare Pages) without a per-site netlify.toml — important for the demo site.
# Exact root only (`/`), so /web/ and the subresources under it are served, not redirected.
printf '/  /web/  302\n' > "$site/_redirects"

# A short, self-contained serving guide at the tarball root — the one hard requirement
# (COOP/COEP) plus the turnkey command and the per-host header recipes.
cat > "$site/README.md" <<'EOF'
# nxvim edit-host — static site

The nxvim editor compiled to WebAssembly: a fully client-side editor, no server-side
code. These are plain static files — `web/` and `dist/` as siblings.

## Serve it

The one hard requirement is **cross-origin isolation**: the editor's run loop parks on a
`SharedArrayBuffer`, which the browser only grants when every response carries

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Resource-Policy: same-origin
```

Without them the page still loads but degrades to the slower postMessage transport and
**timers never fire**. `.wasm` must also be served as `application/wasm`.

**Turnkey (Node, no deps):** a reference server that sets exactly these headers ships in
the tarball —

```sh
node web/serve.mjs            # then open http://localhost:8088/web/
```

**Netlify / Cloudflare Pages / any `_headers` host:** the `_headers` file at this root
already sets all three for `/*`. Redirect `/` → `/web/`.

**nginx:**

```nginx
location / {
  add_header Cross-Origin-Opener-Policy   "same-origin"  always;
  add_header Cross-Origin-Embedder-Policy "require-corp" always;
  add_header Cross-Origin-Resource-Policy "same-origin"  always;
  types { application/wasm wasm; }
}
```

**Apache (`.htaccess`):**

```apache
Header always set Cross-Origin-Opener-Policy   "same-origin"
Header always set Cross-Origin-Embedder-Policy "require-corp"
Header always set Cross-Origin-Resource-Policy "same-origin"
AddType application/wasm .wasm
```

The app lives under `/web/` (its imports resolve relative to that document URL), so send
the bare root there: open `…/web/`, not `…/`.
EOF

echo "assembled static edit-host site → $site"
