-- ~~~ bemtvi btv.cmdline_complete playground: command-line completion ~~~
--
-- Run it (from the repo root) against the sample buffer:
--
--     BEMTVI_CONFIG=examples/cmdline-completion \
--       cargo run -p bemtvi -- examples/cmdline-completion/sample.txt
--
-- `btv.cmdline_complete` is the wildmenu on the unified float-list widget — its
-- FIFTH orchestration (picker / btv.ui.select / insert-completion / the docs
-- sidebar being the prior four; docs/specs/2026-06-14-btv-ui-float-widget.md,
-- docs/plans/2026-06-16-cmdline-completion.md). Press <Tab> on an ex command line
-- (`:`) and a fuzzy list of matching command NAMES floats just above the line,
-- anchored under the command-name token.
--
-- Engine in Rust core, policy in Lua: core extracts the token, fuzzy-ranks the
-- catalog (matched chars are highlighted), renders the menu, and applies the
-- accept; the bundled `btv.cmdline_complete` plugin owns the curated command
-- catalog. No input loop runs in Lua (ADR 0002 rule 4).
--
-- WHAT TO TRY (open the command line with `:` first):
--   :e<Tab>            float a list of commands matching `e` (edit, enew, …)
--   :tab<Tab>          narrow to the tab-* family
--   keep typing        the open list narrows LIVE against what you type
--                      (`:e<Tab>` then `d` → just `edit`)
--   <Tab> / <C-n> / <Down>   cycle the highlight forward — a docs float showing the
--                            highlighted command's synopsis + help floats beside it
--   <S-Tab> / <C-p> / <Up>   cycle the highlight backward
--   <CR>               accept the highlighted command (rewriting the token) and
--                      RUN it; with nothing highlighted, run the typed line as-is
--   <Esc>              dismiss the wildmenu but keep the command line open
--                      (a second <Esc> then cancels the line)
--
-- The popup opens with NOTHING highlighted (noselect) — so the first <Tab>
-- highlights the top match and the first <S-Tab> the bottom one, and <CR> keeps
-- running the typed line until you actually pick a row.
--
-- A worked example against this buffer:
--   :ene<Tab>          float the list — `enew` is the top fuzzy match for `ene`
--   <Tab>              highlight `enew`
--   <CR>               accept + run :enew → a new empty buffer replaces this one
--
-- THE UNIFIED PAYOFF — a plugin command appears like a built-in:
--   :Greet<Tab>        the `:Greet` command registered below shows in the list, and
--                      its `desc` is the docs float text — no extra wiring
--
-- ARGUMENT COMPLETION — option names after `:set` (with docs):
--   :set <Tab>         float the WHOLE option catalog (every settable option)
--   :set nu<Tab>       narrow to options matching `nu` (number, numberwidth, …)
--   :setlocal ts<Tab>  `:setlocal` shares the option-argument completer
--   <Tab>              highlight a row — the docs float shows the option's name +
--                      abbreviation, its scope + kind, and a one-line description
--   <CR>               accept the highlighted option name AND run the line, exactly
--                      as it does for a command name (`:set number` is complete on
--                      its own). Only the file-path PICKER below pastes without
--                      running — for a value form like `:set tabstop=4`, dismiss
--                      the wildmenu with <Esc> and finish typing the line.
--
-- FILE-PATH COMPLETION — a fuzzy PICKER for file/dir arguments:
--   :e <Tab>           open the btv.picker overlay OVER the still-open command line (a
--                      centered fuzzy finder titled "Select file", with a preview
--                      pane), listing the cwd with directories first — the SAME-LEVEL
--                      entries ranked ahead of anything deeper. The `:` line stays
--                      open underneath; the picker grabs the keys while it lives.
--   :e src/ed<Tab>     the picker opens already seeded with `src/ed`, listing `src/`
--                      filtered to `ed…`
--   type in the picker narrow the listing; `/` descends into a directory (so does
--                      confirming one — its preview shows the directory's contents)
--   inside a directory a "<select directory>" row tops the list: pick it to use that
--                      directory as the path (e.g. `:cd src/`) instead of descending
--   <CR> on a file     PASTE the chosen path into the command line (it does NOT run
--                      the command) — the line becomes e.g. `:e src/foo.rs`, and you
--                      press <CR> again to actually open it (or keep editing / Tab)
--   <Esc>              close the picker, leaving the command line as you left it (a
--                      second <Esc> cancels the line)
--   :split / :vsplit / :tabedit / :read / :source / :pedit / … hand off the same way
--   :cd <Tab>          the dir-taking commands (`:cd` / `:lcd` / `:tcd`) list
--                      directories only, titled "Select directory"
--
-- NAME ARGUMENT COMPLETION — buffers, color schemes, highlight groups (inline, like
-- `:set`, sourced from what the editor already knows so it can never drift):
--   :buffer <Tab>      list the loaded buffers by name (`:bdelete` / `:bwipeout`
--                      share it); type to fuzzy-narrow, <CR> accepts the highlighted
--                      name and runs the line
--   :colorscheme <Tab> list every available color scheme — the bundled `bemtvi` plus
--                      any `colors/<name>.lua` on the runtimepath (a plugin theme
--                      shows the instant it's installed)
--   :highlight <Tab>   list the defined highlight groups (e.g. `:highlight Comment`)
--   :setfiletype <Tab> list the filetypes bemtvi recognizes (`rust`, `lua`, `python`, …)
--   :TSInstall <Tab>   list the tree-sitter languages bemtvi can highlight (`:TSUpdate`
--                      shares it) — takes several, so every argument completes
--   :autocmd <Tab>     list the autocmd events bemtvi emits (`:autocmd BufWrite<Tab>`);
--                      `:augroup <Tab>` lists the defined autocommand groups
--   :put <Tab>         list the registers that currently hold content (with a preview)
--   :move <Tab>        list address landmarks — `.`, `$`, `0`, and the current
--                      buffer's marks as `'x` (`:copy` shares it)
--
-- MODIFIER WRAPPERS — completion recurses through `:vertical` / `:tab` / `:silent`:
--   :vertical spl<Tab> the modifier is stripped and the NESTED command completes —
--                      `split` is offered (not treated as an argument)
--   :tab e <Tab>       the wrapped `:e` hands its file argument to the picker, and
--                      confirming keeps the `tab ` prefix (`:tab e src/foo.rs`)
--   :silent <Tab>      chained modifiers recurse, e.g. `:tab vertical split`
--
-- The completer dispatches on the command word: `:set`/`:setlocal` arguments
-- complete option names, `:buffer`/`:colorscheme`/`:highlight`/`:setfiletype`/`:TSInstall`
-- and the `:autocmd`/`:augroup`/`:put`/`:move` first argument complete their respective
-- names (each from an authoritative in-memory source, so it can never drift from what
-- the command accepts); a `:vertical`/`:tab`/`:silent` modifier is stripped and the
-- wrapped command completes; file/dir commands hand off to the picker (above); any
-- other command's arguments have no completer yet, so the wildmenu just stays closed.

-- Command-line completion is ON BY DEFAULT in the interactive editor, so this call
-- is optional — it's here to TUNE the engine. A bare `setup {}` is the default
-- (`docs = true` — the synopsis/help float beside the highlighted row); pass
-- `docs = false` for a names-only wildmenu. (A config that re-runs setup wins over
-- the default, since the last setup call applies.)
btv.cmdline_complete.setup {}

-- A plugin command with a `desc`: it joins the wildmenu catalog automatically (via
-- btv.user_command.get()), ranked and previewed exactly like a built-in.
btv.user_command.create("Greet", function()
  btv.notify("Hello from a plugin command!")
end, { desc = "Print a friendly greeting" })
