//! Throwaway generator: emits the differential corpus `verify-width.mjs` checks the web
//! client's `clusterWidth` against — every grapheme cluster from a realistic sample of
//! text and emoji, paired with the width the SERVER assigns it (`unicode-width`, the
//! authority every wire column is measured in). Run:
//! `cargo run -p bemtvi-core --example width_corpus > crates/bemtvi-edithost/web/width-corpus.json`.
//!
//! The client mirrors those widths from generated tables (see `dump_width.rs`); this
//! corpus is what proves the mirror still holds after either side changes.
use unicode_segmentation::UnicodeSegmentation;
use unicode_width::UnicodeWidthStr;

/// Text whose clusters exercise every rule the client reproduces: plain ASCII, CJK and
/// fullwidth forms, combining marks, the Nerd-Font private-use area, box drawing, and
/// each emoji sequence shape (bare, presentation-selected, text-selected, skin-toned,
/// ZWJ-joined, keycapped, flagged).
const SAMPLES: &[&str] = &[
    "let x = 1;",
    "日本語のテキスト",
    "縄県（おきck.json",
    "Ｈｅｌｌｏ, ｗｏｒｌｄ!",
    "e\u{0301}tude cafe\u{0301}",
    "한글 조합",
    "\u{e60b}\u{e61e}\u{f031b} \u{251c}\u{2500}\u{2514}\u{2502}",
    "\u{1f600}\u{1f602}\u{1f60d}",
    "\u{2764}\u{fe0f} \u{2764} \u{2764}\u{fe0e}",
    "\u{2614}\u{fe0e} \u{2614}\u{fe0f} \u{2328}\u{fe0f} \u{26a0}\u{fe0f}",
    "\u{1f934}\u{1f3fc} \u{1f44d}\u{1f3fd} \u{1f9d1}\u{1f3fb}\u{200d}\u{1f4bb}",
    "\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467} \u{1f3f3}\u{fe0f}\u{200d}\u{1f308}",
    "\u{1f1e7}\u{1f1f7} \u{1f1fa}\u{1f1f8} \u{0031}\u{fe0f}\u{20e3}",
    "\u{00a9}\u{fe0f} \u{2122}\u{fe0f} \u{2194}\u{fe0f} \u{23f0}",
    "-- \u{251c} \u{e60b} \u{1f934}\u{1f3fc}b\u{2764}\u{fe0f}emtvi-lo\u{7e04}\u{770c}\u{ff08}\u{304a}\u{304d}ck.json",
];

/// `s` as a JSON string literal, every non-ASCII scalar escaped to `\uXXXX` (surrogate
/// pairs above the BMP) so the corpus file is pure ASCII and diffs readably.
fn json(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            ' '..='~' => out.push(c),
            _ => {
                let mut buf = [0u16; 2];
                for u in c.encode_utf16(&mut buf) {
                    out.push_str(&format!("\\u{u:04x}"));
                }
            }
        }
    }
    out.push('"');
    out
}

fn main() {
    let mut seen: Vec<(String, usize)> = Vec::new();
    for s in SAMPLES {
        for g in s.graphemes(true) {
            if seen.iter().any(|(t, _)| t == g) {
                continue;
            }
            seen.push((g.to_string(), UnicodeWidthStr::width(g)));
        }
    }
    println!("{{");
    println!("  \"_\": \"GENERATED by `cargo run -p bemtvi-core --example width_corpus`. Cluster -> display cells, per the server's unicode-width.\",");
    println!("  \"lines\": [");
    for (i, s) in SAMPLES.iter().enumerate() {
        let comma = if i + 1 < SAMPLES.len() { "," } else { "" };
        println!(
            "    {{ \"text\": {}, \"width\": {} }}{comma}",
            json(s),
            UnicodeWidthStr::width(*s)
        );
    }
    println!("  ],");
    println!("  \"clusters\": [");
    for (i, (g, w)) in seen.iter().enumerate() {
        let comma = if i + 1 < seen.len() { "," } else { "" };
        println!("    {{ \"cluster\": {}, \"width\": {w} }}{comma}", json(g));
    }
    println!("  ]");
    println!("}}");
}
