//! Throwaway generator: emits the differential corpus `verify-width.mjs` checks the web
//! client's `clusterWidth` against — every grapheme cluster from a realistic sample of
//! text and emoji, paired with the width the SERVER assigns it (`unicode::virtcol`'s
//! model, the grid every wire column is measured in — see `server_width`). Run:
//! `cargo run -p bemtvi-core --example width_corpus > crates/bemtvi-edithost/web/width-corpus.json`.
//!
//! The client gets those widths from the same two crates, compiled to wasm
//! (`crates/bemtvi-width`, loaded by `web/width.js`) — so this corpus is not checking a
//! mirror for drift any more, it is checking the WIRING: that the module is built, is
//! actually loaded, and is what the renderer's cell grid is built from. A page that
//! silently fell back to guessing widths would fail here.
use unicode_segmentation::UnicodeSegmentation;
use unicode_width::UnicodeWidthStr;

/// Text whose clusters exercise every rule the client reproduces: plain ASCII, CJK and
/// fullwidth forms, combining marks, the Nerd-Font private-use area, box drawing, and
/// each emoji sequence shape (bare, presentation-selected, text-selected, skin-toned,
/// ZWJ-joined, keycapped, flagged).
const SAMPLES: &[&str] = &[
    "let x = 1;",
    "日本語のテキスト",
    "縄県（おきck.json",
    "Ｈｅｌｌｏ, ｗｏｒｌｄ!",
    "e\u{0301}tude cafe\u{0301}",
    "한글 조합",
    "\u{e60b}\u{e61e}\u{f031b} \u{251c}\u{2500}\u{2514}\u{2502}",
    "\u{1f600}\u{1f602}\u{1f60d}",
    "\u{2764}\u{fe0f} \u{2764} \u{2764}\u{fe0e}",
    "\u{2614}\u{fe0e} \u{2614}\u{fe0f} \u{2328}\u{fe0f} \u{26a0}\u{fe0f}",
    "\u{1f934}\u{1f3fc} \u{1f44d}\u{1f3fd} \u{1f9d1}\u{1f3fb}\u{200d}\u{1f4bb}",
    "\u{1f468}\u{200d}\u{1f469}\u{200d}\u{1f467} \u{1f3f3}\u{fe0f}\u{200d}\u{1f308}",
    "\u{1f1e7}\u{1f1f7} \u{1f1fa}\u{1f1f8} \u{0031}\u{fe0f}\u{20e3}",
    "\u{00a9}\u{fe0f} \u{2122}\u{fe0f} \u{2194}\u{fe0f} \u{23f0}",
    // Sequences `unicode-width` ligatures ACROSS grapheme clusters — Arabic lam-alef,
    // Hebrew alef-lamed, a Lisu tone pair. `virtcol` measures each cluster separately
    // and so counts them 2 columns, not the crate's 1; pinning them here keeps the
    // client on the editor's grid rather than the crate's whole-string answer.
    "\u{644}\u{627} \u{5d0}\u{200d}\u{5dc} \u{a4f8}\u{a4fc}",
    // Devanagari and Thai: clusters that are several codepoints and ONE cell.
    "\u{915}\u{94d}\u{937} \u{e01}\u{e31}\u{e49}",
    "-- \u{251c} \u{e60b} \u{1f934}\u{1f3fc}b\u{2764}\u{fe0f}emtvi-lo\u{7e04}\u{770c}\u{ff08}\u{304a}\u{304d}ck.json",
];

/// `s` as a JSON string literal, every non-ASCII scalar escaped to `\uXXXX` (surrogate
/// pairs above the BMP) so the corpus file is pure ASCII and diffs readably.
fn json(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            ' '..='~' => out.push(c),
            _ => {
                let mut buf = [0u16; 2];
                for u in c.encode_utf16(&mut buf) {
                    out.push_str(&format!("\\u{u:04x}"));
                }
            }
        }
    }
    out.push('"');
    out
}

/// The width the SERVER assigns `s` — `unicode::virtcol`'s model, which walks grapheme
/// clusters and measures each one. NOT `UnicodeWidthStr::width(s)` on the whole string:
/// that additionally ligatures across cluster boundaries (Arabic lam-alef is 1 cell to
/// it, 2 to `virtcol`), and it is the server's grid the client has to match.
fn server_width(s: &str) -> usize {
    s.graphemes(true).map(UnicodeWidthStr::width).sum()
}

fn main() {
    let mut seen: Vec<(String, usize)> = Vec::new();
    for s in SAMPLES {
        for g in s.graphemes(true) {
            if seen.iter().any(|(t, _)| t == g) {
                continue;
            }
            seen.push((g.to_string(), server_width(g)));
        }
    }
    println!("{{");
    println!("  \"_\": \"GENERATED by `cargo run -p bemtvi-core --example width_corpus`. Cluster -> display cells, per the server's unicode-width.\",");
    println!("  \"lines\": [");
    for (i, s) in SAMPLES.iter().enumerate() {
        let comma = if i + 1 < SAMPLES.len() { "," } else { "" };
        println!(
            "    {{ \"text\": {}, \"width\": {} }}{comma}",
            json(s),
            server_width(s)
        );
    }
    println!("  ],");
    println!("  \"clusters\": [");
    for (i, (g, w)) in seen.iter().enumerate() {
        let comma = if i + 1 < seen.len() { "," } else { "" };
        println!("    {{ \"cluster\": {}, \"width\": {w} }}{comma}", json(g));
    }
    println!("  ]");
    println!("}}");
}
