[package]
name = "nxvim-rpc"
description = "Async msgpack-RPC transport for nxvim (neovim-compatible message framing)."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
rmpv.workspace = true
tokio.workspace = true
