// Amalgamate one or more bemtvi plugin trees into a SINGLE Lua file that registers each
// module under `package.preload[...]`. The browser build's Lua VM has no filesystem and an
// empty runtimepath, so a multi-file plugin (`require("bemtvi-line.config")` etc.) can't
// resolve through `package.path`. Instead we concatenate every module's source into one
// chunk: sourcing it registers each module in the preload table, and the stock `require`
// (whose first searcher is always `package.preload`) then resolves them from memory.
//
// The wrapper is sound for any module: a valid Lua chunk is a valid function body, so a
// file's `local M = {} … return M` becomes the preload function verbatim — top-level
// locals stay module-scoped, and the file's `return` becomes the module value `require`
// hands back. (Verified end-to-end by verify-plugin-bundle.mjs.)
//
// Per-plugin IDENTITY. A module compiled inline shares the whole bundle's chunk name
// (`@init.lua`, the name `source_config` gives it), so persistence attribution — which
// derives a plugin's `btv.shada` namespace from the calling chunk's `@<path>` source under a
// registered runtimepath entry — can't tell one bundled plugin from another and, with an
// empty runtimepath, raises "this caller attributes to no plugin" (a plugin that calls
// `btv.shada.plugin()` / `btv.view.create{ persist }` at load, e.g. bemtvi-tree's session
// persistence, crashes the whole config). So instead of an inline function literal we compile
// each module through `load(<src>, "@<root>/lua/<rel>")` — giving it a distinct, plugin-scoped
// chunk name — and register a synthetic runtimepath root (`btv._add_rtp`) per plugin. That
// reproduces, in the browser, exactly the native attribution: a bundled plugin resolves to its
// own install-dir-basename namespace, isolated from every other plugin and from the user config.
//
// Usage:
//   node amalgamate-plugins.mjs [-o OUT.lua] PLUGIN_DIR [PLUGIN_DIR ...]
// Each PLUGIN_DIR is a plugin repo root containing a `lua/` tree. With no -o, prints to
// stdout. Also exported as `amalgamate(pluginDirs)` for direct use by the verifier.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, join, relative, sep } from "node:path";

// Wrap `body` as a Lua long-bracket string with a level whose closer can't appear inside it,
// so any module source (including one with its own `]]` / `]=]` long strings) round-trips. A
// leading newline is prepended: Lua drops the first newline after the opener, so the module's
// own line 1 stays line 1 and error tracebacks point at the real source line.
function luaLongString(body) {
  const content = `\n${body}`;
  let level = 0;
  while (content.includes(`]${"=".repeat(level)}]`)) level++;
  const eq = "=".repeat(level);
  return `[${eq}[${content}]${eq}]`;
}

// Map a .lua path (relative to a plugin's `lua/` dir) to its Lua module name, matching the
// default `package.path` search order `?.lua;?/init.lua`:
//   foo.lua          -> foo
//   foo/init.lua     -> foo
//   foo/bar.lua      -> foo.bar
//   foo/bar/init.lua -> foo.bar
function moduleName(rel) {
  let p = rel.slice(0, -".lua".length); // strip the .lua we already filtered on
  const initSuffix = `${sep}init`;
  if (p.endsWith(initSuffix)) p = p.slice(0, -initSuffix.length);
  return p.split(sep).join(".");
}

// Yield every .lua file under `dir`, recursively, sorted for a deterministic bundle.
function* luaFiles(dir, base = dir) {
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) yield* luaFiles(full, base);
    else if (name.endsWith(".lua")) yield { full, rel: relative(base, full) };
  }
}

export function amalgamate(pluginDirs) {
  const out = [
    "-- GENERATED by amalgamate-plugins.mjs — do not edit by hand.",
    "-- Registers each plugin module under package.preload so the browser build's",
    "-- require(...) resolves from memory (the wasm VM has no filesystem/runtimepath).",
    "",
  ];
  const seen = new Map(); // module name -> source file, to reject collisions across plugins
  for (const dir of pluginDirs) {
    const luaDir = join(dir, "lua");
    let entries;
    try {
      entries = [...luaFiles(luaDir)];
    } catch {
      throw new Error(`plugin has no lua/ directory: ${dir}`);
    }
    if (!entries.length) throw new Error(`plugin lua/ is empty: ${luaDir}`);
    // A synthetic, browser-only runtimepath root for this plugin. Its basename IS the plugin's
    // persistence namespace (matching the native "install-dir basename" fallback); the absolute
    // `/bemtvi-plugins/` prefix keeps it clear of any real MEMFS path so a stray relative
    // `require` can never resolve against it. Registered once so the plugin's chunks attribute.
    const root = `/bemtvi-plugins/${basename(dir)}`;
    out.push(`if btv and btv._add_rtp then btv._add_rtp(${JSON.stringify(root)}) end`);
    for (const { full, rel } of entries) {
      const mod = moduleName(rel);
      if (!mod) throw new Error(`cannot derive a module name for ${full}`);
      if (seen.has(mod)) throw new Error(`duplicate module "${mod}": ${seen.get(mod)} vs ${full}`);
      seen.set(mod, full);
      const body = readFileSync(full, "utf8");
      // Compile the module through `load` with a plugin-scoped `@<root>/lua/<rel>` chunk name so
      // its `btv.shada` / persistence calls attribute to this plugin (see the header note). `load`
      // returns the module's function verbatim — the preload searcher hands it straight to
      // `require`, whose `...` still carries the module name / path exactly as before.
      const chunkName = `@${root}/lua/${rel.split(sep).join("/")}`;
      out.push(
        `package.preload[${JSON.stringify(mod)}] = ` +
          `assert(load(${luaLongString(body)}, ${JSON.stringify(chunkName)}))`,
      );
      out.push("");
    }
  }
  return out.join("\n");
}

// CLI entry — run only when invoked directly, not when imported by the verifier.
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  let outPath = null;
  const dirs = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "-o") outPath = args[++i];
    else dirs.push(args[i]);
  }
  if (!dirs.length) {
    console.error("usage: amalgamate-plugins.mjs [-o OUT.lua] PLUGIN_DIR [PLUGIN_DIR ...]");
    process.exit(2);
  }
  const bundle = amalgamate(dirs);
  if (outPath) {
    writeFileSync(outPath, bundle);
    console.error(`wrote ${outPath} (${dirs.length} plugin${dirs.length > 1 ? "s" : ""})`);
  } else {
    process.stdout.write(bundle);
  }
}
