// btv-sw.js — the browser half of `btv.http.mount`.
//
// A tab cannot bind a TCP port, so where the native build runs a listener, the web build
// runs THIS: a Service Worker that intercepts `fetch` for the reserved `/plugin/` namespace
// on the page's own origin and relays each request to the edit-host. Same
// HttpServerRequest/HttpServerReply contract as the native listener, so a plugin's Lua is
// identical between worlds — only `mount:url()` differs (this origin, not 127.0.0.1:<port>).
//
// WHY a Service Worker and not plain postMessage: the point of the feature is a REAL URL —
// one an <iframe>, an <img src>, a window.open, or a stylesheet @import can load. Only a SW
// makes ordinary browser loads resolve to editor-generated bytes. postMessage could hand the
// page some data, but nothing else in the platform would treat it as a URL.
//
// TOPOLOGY. The edit-host wasm lives in a dedicated Worker, and a SW is a third context that
// cannot reach it — so this relays through a window client, which owns the ring to the
// Worker:
//
//   fetch /plugin/x/  ─► [this]  ─postMessage+MessageChannel─►  window
//                                                                 └─ring frame─► worker
//                                                                       └─► wasm ─► Lua
//                        ◄────────── port.postMessage(reply) ◄────────────┘
//
// See docs/plans/2026-07-14-btv-http-mount.md.

// Everything under here is the editor's; everything else on the origin is the site's own and
// must fall through untouched (the page, the wasm, the worker script — including this one).
const MOUNT_PREFIX = "/plugin/";

// How long to hold a request before giving the browser a 504.
//
// This is a BACKSTOP, not the contract. A mount's `opts.timeout` is enforced by the editor
// itself (Lua arms a deadline per request and answers 504), so it applies identically here
// and natively — this build needs no listener to know about it. What is left for this to
// cover is the case that deadline cannot: the editor never runs it. That means a wedged
// tick, or the postMessage fallback transport, where Lua timers never fire at all.
//
// Deliberately far longer than any sane `opts.timeout`: firing early would cut off a
// legitimately slow handler that the editor was going to answer. It caps `opts.timeout` in
// the pathological case of a mount asking for more than this — worth knowing, not worth
// plumbing a per-mount value through the Service Worker for.
const BACKSTOP_MS = 300000; // 5 minutes

// Take over as soon as we are installed rather than waiting for the next navigation: a mount
// published in the page's own init.lua would otherwise 404 until a reload, which reads as
// "the feature is broken" on a first visit.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => event.waitUntil(self.clients.claim()));

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith(MOUNT_PREFIX)) return;
  event.respondWith(routeToEditHost(event.request, url));
});

// Relay one request to the edit-host and await its reply. Every failure mode answers with a
// status rather than a hang or an empty 200 — a mount that cannot be served must SAY so.
async function routeToEditHost(request, url) {
  const client = await pickClient();
  if (!client) {
    // No page is running the editor (every tab closed, or this SW outlived them). There is
    // nothing that could answer, and 503 is the honest way to say it.
    return plain(503, "bemtvi: no edit-host client is running\n");
  }

  let body;
  try {
    body = new Uint8Array(await request.arrayBuffer());
  } catch {
    body = new Uint8Array(0);
  }

  const channel = new MessageChannel();
  const reply = new Promise((resolve) => {
    channel.port1.onmessage = (e) => resolve(e.data);
  });

  client.postMessage(
    {
      type: "btv-http-request",
      request: {
        method: request.method,
        // The FULL path: the editor splits /plugin/<name>/<rest> itself, with the same code
        // the native listener uses, so the two worlds cannot disagree about what req.path is.
        path: url.pathname,
        query: url.search.replace(/^\?/, ""),
        headers: [...request.headers].map(([name, value]) => [name, value]),
        body: [...body],
      },
    },
    [channel.port2]
  );

  const res = await Promise.race([reply, timeout(BACKSTOP_MS)]);
  if (!res) return plain(504, "bemtvi: the editor never answered this request\n");

  const headers = new Headers(res.headers || []);
  // The editor page is cross-origin isolated (COEP: require-corp — the SharedArrayBuffer
  // prerequisite), and a document embedded in such a page must assert COEP itself or the
  // browser refuses to load it. That makes an <iframe> of a mount — the whole point of
  // serving a real URL — fail without these. The editor knows it is isolated; a plugin
  // should not have to, so we default them here and let an explicit header win.
  if (!headers.has("cross-origin-embedder-policy")) {
    headers.set("cross-origin-embedder-policy", "require-corp");
  }
  if (!headers.has("cross-origin-resource-policy")) {
    headers.set("cross-origin-resource-policy", "same-origin");
  }
  return new Response(res.body && res.body.length ? new Uint8Array(res.body) : null, {
    status: res.status,
    headers,
  });
}

// The window client to relay through — a window that is actually RUNNING the editor, found
// by asking, not by guessing from focus.
//
// The subtlety this exists for: the tab that OPENS a mount URL is itself a same-origin,
// focused window client. Picking by focus/visibility would relay the request to that very
// tab — which is loading the mount page and has no relay listener — so nothing ever answers
// and the load spins. Instead we probe every window: only a tab running the editor's message
// handler replies, so the requesting tab (and any other non-editor page on the origin) is
// never chosen. With several editor tabs open, the first to answer wins — fine, any of them
// can serve.
async function pickClient() {
  const clients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
  if (clients.length === 0) return null;
  // The first window to answer "yes" wins. A non-editor tab never answers, so its probe only
  // settles (to null) at the timeout — an editor's fast "yes" always beats that. Null when no
  // editor answers at all (every tab closed, or all still mid-navigation).
  const winner = await Promise.race([...clients.map(probeIsEditor), timeout(PROBE_TIMEOUT_MS)]);
  return winner || null;
}

// Ask one window whether it is running the editor. Resolves with the client if it says yes,
// else `null` (a non-editor page, or a tab mid-navigation, never replies — so it times out).
function probeIsEditor(client) {
  return new Promise((resolve) => {
    const channel = new MessageChannel();
    const done = setTimeout(() => resolve(null), PROBE_TIMEOUT_MS);
    channel.port1.onmessage = (e) => {
      clearTimeout(done);
      resolve(e.data && e.data.btvEdithost ? client : null);
    };
    client.postMessage({ type: "btv-edithost-probe" }, [channel.port2]);
  });
}

// How long to wait for a window to identify itself as the editor. A local postMessage
// round-trip is sub-millisecond; this only bounds the case where NO editor is running.
const PROBE_TIMEOUT_MS = 2000;

const timeout = (ms) => new Promise((resolve) => setTimeout(() => resolve(null), ms));

const plain = (status, text) =>
  new Response(text, { status, headers: { "content-type": "text/plain; charset=utf-8" } });
