[package]
name = "nxvim-core"
description = "Editor model and logic for nxvim (buffers, modes, motions, operators, rendering)."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
ropey.workspace = true
unicode-width.workspace = true
unicode-segmentation.workspace = true
