-- ~~~ nxvim image previews: open an image, see the picture ~~~
--
-- Run it (from the repo root) against the sample image:
--
--     NXVIM_CONFIG=examples/image-preview \
--       cargo run -p nxvim -- examples/image-preview/sample.png
--
-- With `'imagepreview'` on, opening a file whose extension is a known image type
-- (png/jpg/jpeg/gif/bmp/webp/tiff/ico/tga/qoi/pnm) shows the *picture* instead of
-- the file's raw bytes. The buffer is inert — its bytes are never loaded as text —
-- so it is a preview, not an editable buffer.
--
-- The TUI renders the image with the best graphics protocol your terminal speaks
-- (Kitty / Sixel / iTerm2), falling back to unicode half-blocks on a terminal that
-- supports none. So for a real picture (not a blocky approximation), run this in a
-- graphics-capable terminal — e.g. Kitty, WezTerm, Ghostty, or iTerm2.
--
-- The GUI client (`nxvim-gui`) renders the picture as a true GPU texture — always
-- crisp, no terminal protocol involved:
--
--     NXVIM_CONFIG=examples/image-preview \
--       cargo run -p nxvim-gui -- examples/image-preview/sample.png
--
-- The picture is fit to the window (aspect-preserving, centered) and re-decoded
-- when the file changes on disk, same as the TUI.
--
-- The web client (the wasm edit-host) renders it too: it fetches the bytes
-- out-of-band (the editor core never reads them — the redraw carries only the
-- path) and paints an <img>, fit to the window body and centered. Open an image
-- you've stored in its OPFS sandbox (e.g. `:e /sample.png`) with the option on.
-- Browsers can't show tga/qoi/pnm, so those fall back to a visible placeholder
-- there (the TUI/GUI render them via the `image` crate).
--
-- OVER A DAEMON (`:connect` / `--connect-daemon`): the editor runs local but the
-- files live on the remote host, so the native TUI/GUI can't open `sample.png` off
-- their own disk. They fetch the bytes out-of-band over the editor RPC, exactly like
-- the web client — the redraw marker flags the preview `remote` and the client
-- requests `nxvim_image_read`. So previewing a *remote* image works the same way,
-- with no config change; a brief "[image: loading …]" shows until the bytes arrive.
--
-- TRY IT:
--   :e sample.png         open the image (this dir's sample) — preview appears
--   :e some-other.jpg     any image file works
--   :e init.lua           a NON-image opens as ordinary text, unchanged
--   :set noimagepreview   turn it off; now :e sample.png shows the raw bytes
--
-- The option is a normal nx.* option, so `nx.o` / `vim.o` / `:set` all reach it.

-- Turn previews on (off by default). `nx.o` is the canonical surface; `vim.o`
-- and `:set imagepreview` are equivalent.
nx.o.imagepreview = true

-- Nothing else is needed — opening an image is all it takes. A line-number gutter
-- is left off here so the picture fills the window body.
vim.o.number = false
